name: Production Build (Build and Push Images)

on:
  push:
    branches:
      - 'master'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:

      - name: 🛎️ Checkout
        uses: actions/checkout@v4
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build docker image
        run: docker compose -f docker-compose.yml -f docker-compose.prod.yml build

      - name: Push frontend docker image
        run: docker push ghcr.io/maede97/qr-code-generator-frontend:latest

      - name: Push backend docker image
        run: docker push ghcr.io/maede97/qr-code-generator-backend:latest

  notify-server:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Call webhook to update server
        run: |
          curl -H "Authorization: Bearer ${{secrets.BEARER_TOKEN}}" ${{ secrets.WEBHOOK_URL }}